---
# roles/swarm_manager/tasks/main.yml
- name: Initialize Docker Swarm on manager
  shell: docker swarm init --advertise-addr {{ ansible_host }}
  register: swarm_init
  failed_when: swarm_init.rc != 0 and "This node is already part of a swarm" not in swarm_init.stderr
  changed_when: "'This node joined a swarm as a manager' in swarm_init.stdout"
  become: yes

- name: Get worker join token
  shell: docker swarm join-token worker -q
  register: worker_token
  become: yes 

- name: Save worker token as fact
  set_fact:
    swarm_worker_token: "{{ worker_token.stdout }}"